### ISSUE TITLE
Deleting Products/Data Sets from Inventory

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#203] opened 2016-04-11 19:54 UTC
The inventory is a living document, even after it's marked as "up to date." When a user deletes an inventory item, it's marked as "Obsolete" in Analysis and flagged as obsolete/is deleted instead of being deleted in the database. In the Inventory, we still need to determine how this will appear and behave.

**Comment by MakotoTheKnight** [comment] 2016-04-11 19:58
Soft deletion can accomplish this either with us managing the deletion calls or via the [Paranoia](https://github.com/rubysherpas/paranoia) gem.  We will still bring back the value but consider it "deleted" in the view.

Does this also imply that we will allow an undeletion of the inventory item?

**Comment by jkshepperson** [comment] 2016-05-06 18:25
this seems like a duplicate of #292...can @MakotoTheKnight and @candyj0311 confirm? if so - feel free to add these comments to 292 so we have the full info of the task in the ticket!

**Comment by candyj0311** [comment] 2016-05-06 18:33
Yes, this is a duplicate.

**Closed** 2016-05-06 18:35 UTC
Labels: enhancement
