### ISSUE TITLE
Add product to schema in Analysis modal

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#235] opened 2016-04-15 21:46 UTC
Facilitators can add a product or data set to a schema (PD category) in the Analysis as evidence. 

They should click the "Add Product" link which makes a modal appear. They choose product(s) or data set(s) from the modal and it is added to the Data/Product entry field. 

We need to link the products/data sets from the Inventory connected to the Analysis.

**Comment by HeyCat** [comment] 2016-04-20 15:30
![analysis_add_product](https://cloud.githubusercontent.com/assets/5464910/14680407/3c57aff6-06eb-11e6-94c4-4d1bdac1586e.png)
![analysis_add_product_select](https://cloud.githubusercontent.com/assets/5464910/14680408/3c6547e2-06eb-11e6-92e8-092e9df58ba5.png)

**Comment by candyj0311** [comment] 2016-04-20 15:44
If there are lots of products, we should use pagination for every 20 as we do in the main UI.

**Comment by jkshepperson** [comment] 2016-05-02 15:44
Closing issue because it is a duplicate of #267  and has been merged and represented in that ticket.

**Closed by jkshepperson** 2016-05-02 15:44 UTC
Labels: development
