### ISSUE TITLE
Invited New Participant workflow does not add the participants to the Inventory

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#295] opened 2016-05-03 15:49 UTC
When creating a new inventory or viewing an inventory's dashboard - if you try to 'Invite New Participants' and enter a new user's information into the modal, the user does not seem to appear with the inventory. However, their information does appear in the 'Manage Permissions' modal. This new user can't access the inventory. 

Steps to reproduce: 
1. Login and create an inventory
2. Select to 'Invite New Participant' and add a user not listed in the participant list.
3. Click Add to District to save the information
- note: the user will not display in the participants list
- the added user as no way to 'accept' the invitation.
- the user does appear in the 'manage permissions' modal but cannot access the invenotry

**Comment by MakotoTheKnight** [comment] 2016-05-04 21:34
I've done some digging on this and I'm reasonably certain that it's not a bug.  The behavior is the same for assessments and analyses.

What happens here is that the "Invite New Participant" listing is pulling the list from all non-invited participants within the district of your inventory; as a consequence, participants are _removed_ from that list if they are invited to that specific inventory.

Below is a GIF displaying this - apologies on the file size.

![anim](https://cloud.githubusercontent.com/assets/1821302/15030023/709ce7d6-120d-11e6-9231-b5ec10503d46.gif)

The behavior may not be desirable, but from what I can ascertain, it's not malfunctioning.

To the point of a user not being able to accept the invitation:  this may stem from the case in which emails don't appear to be sent out on staging, whereas locally I can see emails being sent.  We'll want to look into that angle a lot closer going forward.

**Comment by jkshepperson** [comment] 2016-05-06 17:50
@MakotoTheKnight : would you recommend then creating a new ticket if we wish to change the existing functionality for this or updating the existing ticket if we want changes made?

**Comment by MakotoTheKnight** [comment] 2016-05-06 19:25
@jkshepperson:  I believe updating the existing ticket would be fine.  #288 covers a lot of what we intend to change and it would likely be a good place to tackle this particular issue.

**Comment by MakotoTheKnight** [comment] 2016-10-17 22:04
Any pending issues with this still existing may be covered by the new Unified Permissions Scheme.  I'll close this out for now and if a new issue pops up, we can tackle it from there.

**Closed** 2016-10-17 22:04 UTC
Labels: bug
